import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NavbarPersonal from "@/components/navbarPersonal";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="es" data-mode="dark">
			<body className={inter.className+" bg-white dark:bg-black"}>
				<NavbarPersonal />
				{children}
			</body>
		</html>
	);
}
